# Site metadata
title: Manual do Acólito do Missal
description: Missal e orientações

# Use Minimal Mistakes via remote_theme (works on GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes"

# Minimal Mistakes theme settings
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Plugins (GitHub Pages–compatible)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-readme-index

# Apply layout defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: true
      toc_label: "Índice"
      toc_icon: "list"
      toc_sticky: true

# Search
search: true

# Pagination
paginate: 10
paginate_path: /page:num/

# Archive settings
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
